config/routes.rb
Rails.application.routes.draw do
  resources :reporters
  get '/help',         to: 'static_pages#help'
  get '/about',        to: 'static_pages#about'
  get '/contact_us',   to: 'static_pages#contact_us'
  devise_for :users
  resources  :media
  root "static_pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/medium.rb
class Medium < ApplicationRecord
  has_many :reporters
  before_save { self.furigana.gsub!(/\s+/, '') }
  validates :name,        presence: true
  validates :furigana,    presence: true,
                          format: { with: /\A\s*[ぁ-ろわをんゔー]+\s*\z/,
                                    message: 'は、ひらがなで記してください' }
  validates :website_url, url: { allow_blank: true,
                                 schemes: %w(http https),
                                 public_suffix: true,
                                 no_local: true }
end

app/models/reporter.rb
class Reporter < ApplicationRecord
  belongs_to :medium, optional: true
  has_one_attached :portrait
  enum :desirability,
    { highly:      2,
      somewhat:    1,
      neutral:     0,
      not_very:   -1,
      not_at_all: -2
    },
    default: :neutral
  # String#my_prettify!: config/initializers/string_extensions.rb
  before_validation -> { self.name.my_prettify!; self.furigana.my_prettify! }, on: [:create, :update]
  validates :name,        presence: true
  validates :furigana,    presence: true,
                          format: { with: /\A[\p{Hiragana}ー]+( [\p{Hiragana}ー]+)*\z/,
                                    message: 'は、ひらがなで記してください' }
  validate :validate_name_not_include_nakaten
  validate :validate_furigana_not_include_nakaten
  validate :validate_medium_id_based_on_independent
  validate :portrait_source_presence_if_portrait_attached

private

  def validate_name_not_include_nakaten
    if name.match?(/・/)
      errors.add(:name, "姓と名の区切りは「・」ではなく、空白にしてください")
    end
  end

  def validate_furigana_not_include_nakaten
    if furigana.match?(/・/)
      errors.add(:furigana, "振り仮名の区切りは「・」ではなく、空白にしてください")
    end
  end

  def validate_medium_id_based_on_independent
    if independent? && medium_id.present?
      errors.add(:medium_id, "独立である場合は、メディアは指定できません")
    elsif !independent? && (medium_id.nil? || !Medium.exists?(medium_id))
      errors.add(:medium_id, "独立でない場合は、メディアを指定してください")
    end
  end

  def portrait_source_presence_if_portrait_attached
    if portrait.attached? && portrait_source.blank?
      errors.add(:portrait_source, "顔写真が添付された時は、明記してください")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

private

  def logged_in?
    !!current_user
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find session[:user_id]
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_medium, only: %i[ show edit update destroy ]

  # GET /media or /media.json
  def index
    @media = Medium.all
  end

  # GET /media/1 or /media/1.json
  def show
    respond_to do |format|
      format.html { redirect_to media_url }
      format.json { render :show, status: :ok, location: @medium }
    end
  end

  # GET /media/new
  def new
    @medium = Medium.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media or /media.json
  def create
    @medium = Medium.new(medium_params)

    respond_to do |format|
      if @medium.save
        format.html { redirect_to media_url, notice: "Medium was successfully created." }
        format.json { render :show, status: :created, location: @medium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1 or /media/1.json
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.html { redirect_to media_url, notice: "Medium was successfully updated." }
        format.json { render :show, status: :ok, location: @medium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1 or /media/1.json
  def destroy
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to media_url, notice: "Medium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medium
      @medium = Medium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medium_params
      params.require(:medium).permit(:name, :furigana, :website_url)
    end
end

app/controllers/reporters_controller.rb
class ReportersController < ApplicationController
  before_action :set_reporter, only: %i[ show edit update destroy ]

  # GET /reporters or /reporters.json
  def index
    @reporters = Reporter.all
    # @reporters = Reporter.paginate page: params[:page], per_page: 10
    # TODO: paginate を復活する
  end

  # GET /reporters/1 or /reporters/1.json
  def show
  end

  # GET /reporters/new
  def new
    @reporter = Reporter.new
  end

  # GET /reporters/1/edit
  def edit
  end

  # POST /reporters or /reporters.json
  def create
    @reporter = Reporter.new(reporter_params)
    @reporter.portrait.attach params[:reporter][:portrait]

    respond_to do |format|
      if @reporter.save
        format.html { redirect_to reporter_url(@reporter), notice: "Reporter was successfully created." }
        format.json { render :show, status: :created, location: @reporter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reporter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reporters/1 or /reporters/1.json
  def update
    respond_to do |format|
      if @reporter.update(reporter_params)
        format.html { redirect_to reporters_url, notice: "Reporter was successfully updated." }
        format.json { render :show, status: :ok, location: @reporter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reporter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reporters/1 or /reporters/1.json
  def destroy
    @reporter.destroy

    respond_to do |format|
      format.html { redirect_to reporters_url, notice: "Reporter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reporter
      @reporter = Reporter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reporter_params
      params.require(:reporter).permit(:name, :furigana, :medium_id, :desirability,
                                       :portrait, :portrait_source, :portrait_copyright)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end

  def about
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/reporters_helper.rb
module ReportersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.slim
header
  nav.navbar.bg-primary
    .navbar-start
      .dropdown
        div.btn.btn-ghost.lg:hidden[tabindex="0" role="button"]
          svg.h-5.w-5[xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"]
            path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16"]
        ul.menu.menu-sm.dropdown-content.mt-3.p-2.shadow.bg-base-100.rounded-box.w-52[class="z-[1]" tabindex="0"]
          li = link_to 'NGリスト', root_path
          li = link_to 'メディア', media_path
          li = link_to '記者',     reporters_path
          / - if logged_in?
          li
            a ユーザー関連
            ul.p-2
              li = link_to 'パスワード変更', edit_user_password_path
              li = link_to 'ログアウト',     destroy_user_session_path, data: { turbo_method: 'delete' }
              li = link_to 'アカウント削除', user_registration_path,    data: { turbo_method: 'delete' }
              li = link_to 'ログイン',       new_user_session_path
              li = link_to 'アカウント登録', new_user_registration_path
      = link_to 'SMILE-UP.', root_path, id: 'logo', class: 'btn btn-ghost text-3xl font-bold'
    .navbar-center.hidden.lg:flex
      ul.menu.menu-horizontal.px-1
          li = link_to 'NGリスト', root_path
          li = link_to 'メディア', media_path
          li = link_to '記者',     reporters_path
          / - if logged_in?
          li
            details
              summary ユーザー関連
              ul.p-2
                li = link_to 'パスワード変更', edit_user_password_path
                li = link_to 'ログアウト',     destroy_user_session_path, data: { turbo_method: 'delete' }
                li = link_to 'アカウント削除', user_registration_path,    data: { turbo_method: 'delete' }
                li = link_to 'ログイン',       new_user_session_path
                li = link_to 'アカウント登録', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = yield(:title)
      |  | SMILE-UP 指名候補・NG記者登録システム
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    meta[charset="utf-8"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload", defer: true
    = javascript_importmap_tags
  body
    = render 'layouts/header'
    main.container
      = yield
    footer.container-fluid
      | 指名候補・NG記者登録システム
    - if Rails.env.development?
      div
        = debug(params)

app/views/media/_form.html.slim
= form_with(model: @medium) do |form|
  - if @medium.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@medium.errors.count, "error")} prohibited this medium from being saved:"
      ul
        - @medium.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :furigana, style: "display: block"
    = form.text_field :furigana

  div
    = form.label :website_url, style: "display: block"
    = form.text_field :website_url

  div
    = form.submit

app/views/media/_medium.html.slim
tr id="#{dom_id medium}"
  td = medium.name
  td = medium.furigana
  td = link_to medium.website_url, medium.website_url, target: '_blank'
  td
    = link_to '編集', edit_medium_path(medium), class: 'btn btn-info'
    = link_to '削除', medium_path(medium), class: 'btn btn-warning',
                      data: { turbo_method:  :delete,
                              turbo_confirm: '削除しますか?' }

app/views/media/edit.html.slim
h1 報道メディア編集

= render "form", medium: @medium

br

div
  => link_to "Show this medium", @medium
  '|
  =< link_to "Back to media", media_path

app/views/media/index.html.slim
p style="color: green" = notice

h1 報道メディア一覧

#media.table-responsive
  table.table
    thead
      th 名称
      th 読み仮名
      th Webサイト
      th 機能
    tbody
      == render @media

= link_to 'メディアを追加する', new_medium_path, class: 'btn btn-primary'

app/views/media/new.html.slim
h1 New medium

== render "form", medium: @medium

br

div
  = link_to "Back to media", media_path

app/views/reporters/_form.html.slim
= form_with(model: @reporter) do |form|
  - if @reporter.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@reporter.errors.count, "error")} prohibited this reporter from being saved:"
      ul
        - @reporter.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :furigana, style: "display: block"
    = form.text_field :furigana

  div
    = form.label :independent, style: "display: block"
    = form.check_box :independent, { onchange: 'toggleMediumIdField(this)' }

  div
    = form.label :medium_id, style: "display: block"
    = form.collection_select :medium_id, Medium.order(:furigana), :id, :name,
                             { disabled: @reporter.independent? }

  div
    = form.label :desirability, style: "display: block"
    = form.select :desirability,
                  Reporter.desirabilities.keys.map{ |key| [t("activerecord.enums.reporter.desirability.#{key}"), key] }

  div
    = form.label :portrait, style: "display: block"
    = form.file_field :portrait

  div
    = form.label :portrait_source, style: "display: block"
    = form.text_field :portrait_source

  div
    = form.label :portrait_copyright, style: "display: block"
    = form.text_field :portrait_copyright

  div
    = form.submit

javascript:

  function toggleMediumIdField(checkbox) {
    var field = document.getElementById('reporter_medium_id');
    if (checkbox.checked) {
      field.disabled = true;
      field.value = ''; // これにより、medium_idの値がnilに設定される
    } else {
      field.disabled = false;
    }
  }

javascript:
// ページ読み込み時に状態を設定

  document.addEventListener('turbolinks:load', function() {
    toggleMediumIdField(document.getElementById('reporter_independent'));
  });

app/views/reporters/_reporter.html.slim
div id="#{dom_id reporter}"
  - if reporter.portrait.attached?
    = link_to reporter.portrait_source do
      = image_tag reporter.portrait, alt: reporter.name
      - if reporter.portrait_copyright
        small
          = "© #{reporter.portrait_copyright}"
  p
    strong
      = t 'activerecord.attributes.reporter.name'
    =< reporter.name
  p
    strong
      = t 'activerecord.attributes.reporter.furigana'
    =< reporter.furigana
  p
    strong
      = t 'activerecord.attributes.reporter.medium'
    - if reporter.medium_id
      =< link_to reporter.medium.name, medium_path(reporter.medium_id)
    - else
      =< 'なし（独立記者）'
  p
    strong
      = t 'activerecord.attributes.reporter.desirability'
    =< t(reporter.desirability, scope: 'activerecord.enums.reporter.desirability')

app/views/reporters/edit.html.slim
h1 Editing reporter

== render "form", reporter: @reporter

br

div
  => link_to "Show this reporter", @reporter
  '|
  =< link_to "Back to reporters", reporters_path

app/views/reporters/index.html.slim
p style="color: green" = notice

h1 記者一覧
/ TODO: h1 を多言語化する

/ .pagination
/   = will_paginate @reporters
/   paginate を復活する（2 箇所）

#reporters
  - @reporters.each do |reporter|
    == render reporter
    p
      = link_to "この記者のデータを変更する", edit_reporter_path(reporter)

/ .pagination
/   = will_paginate @reporters

= link_to "記者を追加する", new_reporter_path

app/views/reporters/new.html.slim
h1 New reporter

== render "form", reporter: @reporter

br

div
  = link_to "Back to reporters", reporters_path

app/views/reporters/show.html.slim
p style="color: green" = notice

== render @reporter

div
  => link_to "Edit this reporter", edit_reporter_path(@reporter)
  '|
  =< link_to "Back to reporters", reporters_path

  = button_to "Destroy this reporter", @reporter, method: :delete

app/views/static_pages/about.html.slim
h1 StaticPages#about
p Find me in app/views/static_pages/about.html.slim

app/views/static_pages/contact_us.html.slim
h1 StaticPages#contact_us
p Find me in app/views/static_pages/contact_us.html.slim

app/views/static_pages/help.html.slim
h1 StaticPages#help
p Find me in app/views/static_pages/help.html.slim